//! # Rule schema & evaluator
//!
//! `core::ops::rules` models declarative automation rules and evaluates them
//! against VDFS entries. A [`Rule`] is a named condition tree plus a set of
//! action references. This module (task E-01) covers the schema, parsing,
//! validation, and a pure evaluator. Executing a rule set over the library and
//! dispatching its actions is handled by the [`execute`] submodule (task E-02);
//! this module ships no UI (task E-03).
//!
//! Rules deserialize from both JSON and TOML so they can be authored by humans
//! or generated by tooling:
//!
//! ```rust
//! use sd_core::ops::rules::parse_rule_toml;
//!
//! let toml = r#"
//! name = "Large MP4s"
//!
//! [condition]
//! type = "all"
//!
//! [[condition.conditions]]
//! type = "extension"
//! value = "mp4"
//!
//! [[condition.conditions]]
//! type = "size"
//! op = "gt"
//! value = 104857600
//!
//! [[actions]]
//! action = "media.transcode"
//! params = { codec = "h264" }
//! "#;
//!
//! let rule = parse_rule_toml(toml).unwrap();
//! assert_eq!(rule.name, "Large MP4s");
//! ```

mod error;
mod evaluator;
pub mod execute;
mod resolve;
mod schema;

pub use error::{RuleError, RuleResult};
pub use evaluator::{evaluate, select_matching, validate_rule, RuleTarget};
pub use execute::{
	apply_file, discover_matches, run_macro, FileOutcome, LibraryMacroDispatcher, MacroDispatcher,
	MacroExecuteAction, MacroExecuteInput, MacroExecutionJob, MacroExecutionJobOutput,
	MacroExecutionResult, MacroFilePlan, MacroJobState, MacroPhase, MacroPlanItem,
};
pub use resolve::{resolve_effective_tag_names, resolve_rule_target, ResolvedTarget};
pub use schema::{ActionRef, ComparisonOp, Condition, PathMatch, Rule};

/// Parse a rule from JSON and validate it.
///
/// Structural problems (unknown condition `type`, bad comparison operator,
/// negative numeric literals) surface as [`RuleError::Json`]; semantic problems
/// (empty boolean groups, empty action references, uncompilable globs) surface
/// as the corresponding validation variant.
pub fn parse_rule_json(input: &str) -> RuleResult<Rule> {
	let rule: Rule = serde_json::from_str(input).map_err(|e| RuleError::Json(e.to_string()))?;
	validate_rule(&rule)?;
	Ok(rule)
}

/// Parse a rule from TOML and validate it.
///
/// Mirrors [`parse_rule_json`] but for TOML input, surfacing structural failures
/// as [`RuleError::Toml`].
pub fn parse_rule_toml(input: &str) -> RuleResult<Rule> {
	let rule: Rule = toml::from_str(input).map_err(|e| RuleError::Toml(e.to_string()))?;
	validate_rule(&rule)?;
	Ok(rule)
}
