// Auto-generated by scripts/generate-i18n-types.ts — do not edit manually

interface CommonTranslations {
	actions: {
		ok: 'OK';
		cancel: 'Cancel';
		save: 'Save';
		delete: 'Delete';
		close: 'Close';
		confirm: 'Confirm';
		back: 'Back';
		next: 'Next';
		reset: 'Reset';
		submit: 'Submit';
		edit: 'Edit';
		copy: 'Copy';
		move: 'Move';
		rename: 'Rename';
		create: 'Create';
		add: 'Add';
		remove: 'Remove';
		search: 'Search';
		filter: 'Filter';
		sort: 'Sort';
		refresh: 'Refresh';
		retry: 'Retry';
		loading: 'Loading...';
	};
	status: {
		loading: 'Loading...';
		error: 'An error occurred';
		success: 'Success';
		noResults: 'No results found';
		empty: 'Nothing here yet';
		saving: 'Saving...';
		resetting: 'Resetting...';
	};
	units: {
		bytes: 'B';
		kilobytes: 'KB';
		megabytes: 'MB';
		gigabytes: 'GB';
		terabytes: 'TB';
	};
	time: {
		justNow: 'Just now';
		minutesAgo: '{{count}} minutes ago';
		hoursAgo: '{{count}} hours ago';
		daysAgo: '{{count}} days ago';
		yesterday: 'Yesterday';
		today: 'Today';
	};
	comingSoon: 'coming soon';
	create: 'Create';
	cancel: 'Cancel';
	add: 'Add';
}

interface DialogTranslations {
	confirm: {
		title: 'Confirm';
		areYouSure: 'Are you sure?';
	};
	delete: {
		title: 'Delete';
		confirmMessage: 'Are you sure you want to delete this item?';
		confirmMultiple: 'Are you sure you want to delete {{count}} items?';
	};
	rename: {
		title: 'Rename';
		newName: 'New name';
		placeholder: 'Enter new name';
	};
	create: {
		library: {
			title: 'Create Library';
			nameLabel: 'Library Name';
			namePlaceholder: 'My Library';
		};
	};
}

interface ErrorsTranslations {
	LOCATION_NOT_FOUND: 'Location not found';
	LOCATION_ALREADY_EXISTS: 'Location already exists';
	FILE_NOT_FOUND: 'File not found';
	LIBRARY_NOT_FOUND: 'Library not found';
	INSUFFICIENT_PERMISSIONS: 'Insufficient permissions';
	NETWORK_ERROR: 'Network connection failed';
	UNKNOWN: 'An unknown error occurred';
}

interface ExplorerTranslations {
	topBar: {
		sidebar: 'Sidebar';
		navigation: 'Navigation';
		path: 'Path';
		search: 'Search';
		tags: 'Tags';
		wander: 'Wander';
		views: 'Views';
		viewSettings: 'View Settings';
		sort: 'Sort';
		split: 'Split';
		transcode: 'Transcode';
		inspector: 'Inspector';
		newTab: 'New tab (⌘T)';
	};
	viewModes: {
		grid: 'Grid';
		list: 'List';
		media: 'Media';
		masonry: 'Masonry';
		column: 'Column';
		size: 'Size';
		knowledge: 'Knowledge';
		organize: 'Organize';
	};
	sort: {
		sortBy: 'Sort By';
		name: 'Name';
		dateModified: 'Date Modified';
		dateCreated: 'Date Created';
		size: 'Size';
		type: 'Type';
		dateTaken: 'Date Taken';
	};
	viewSettings: {
		title: 'View Settings';
		columnWidth: 'Column Width';
		thumbnailSize: 'Thumbnail Size';
		gridSize: 'Grid Size';
		gapSize: 'Gap Size';
		itemsShown: 'Items Shown';
		showFileSize: 'Show File Size';
		foldersFirst: 'Folders First';
	};
	search: {
		placeholder: 'Search...';
		searchInFolder: 'Search in current folder...';
		searchIn: 'Search in:';
		thisFolder: 'This Folder';
		location: 'Location';
		library: 'Library';
		filters: 'Filters';
		clearSearch: 'Clear Search';
		minChars: 'Type at least 2 characters to search';
		comingSoon: 'Search in {{viewMode}} view coming soon';
	};
	pathBar: {
		indexed: 'Location is indexed';
		notIndexed: 'Not indexed';
		indexedStatus: 'Indexed ({{mode}})';
		enableIndexing: 'Enable Indexing';
		openInspector: 'Open Location Inspector';
		outsideLocation: 'Path is outside any location';
		addLocation: 'Add Location';
		enterPath: 'Enter path...';
		enterSdPath: 'Enter SdPath JSON...';
		noPath: 'No path selected';
	};
	empty: {
		selectLocation: 'Select a location from the sidebar to browse files';
	};
	comingSoon: {
		title: 'Coming Soon';
		networkProtocol: 'Network protocol support (SMB, NFS, SFTP, WebDAV) is currently in development. Check back in a future update!';
	};
	favorites: 'Favorites (coming soon)';
	organize: {
		placeholder: 'Organize view coming soon';
		title: 'Organize';
		keepTab: 'Keep';
		discardTab: 'Discard';
		keepAction: 'Keep this tab';
		discardAction: 'Discard this tab';
		clearAction: 'Clear decisions';
		deleteNow: 'Delete now';
		deleteDialogTitle: 'Permanently delete discarded items?';
		deleteDialogDescription: 'This will permanently delete all direct children currently marked as discard. This cannot be undone.';
		deleteDialogCancel: 'Cancel';
		deleteDialogConfirm: 'Delete permanently';
		previewList: 'Preview list';
		previewVideo: 'Video';
		previewImage: 'Image';
		previewEmpty: 'No items to preview';
		previewMissingVideo: 'No video files in this folder';
		previewMissingImage: 'No image files in this folder';
	};
}

interface OverviewTranslations {
	title: 'Overview';
	selectLibrary: 'Select Library';
	newLibrary: 'New Library';
	librarySettings: 'Library Settings';
	pairDevice: 'Pair Device';
	setupSync: 'Setup Sync';
	refresh: 'Refresh';
	refreshStatistics: 'Refresh Statistics';
	addStorage: 'Add Storage';
	stats: {
		totalStorage: 'Total Storage';
		used: 'used';
		filesIndexed: 'Files Indexed';
		uniqueFiles: 'unique files';
		connectedDevices: 'Connected Devices';
		registeredInLibrary: 'registered in library';
		aiComputePower: 'AI Compute Power';
		librarySize: 'Library Size';
		databaseOnDisk: 'database on disk';
		sidecarStorage: 'Sidecar Storage';
		filesGenerated: 'files generated';
		locations: 'Locations';
		indexedFolders: 'indexed folders';
		tags: 'Tags';
		organizationLabels: 'organization labels';
	};
	topsRank: {
		extreme: 'Extreme';
		veryHigh: 'Very High';
		high: 'High';
		moderate: 'Moderate';
		low: 'Low';
	};
}

interface SettingsTranslations {
	general: {
		title: 'General';
		description: 'Configure general application settings.';
		language: 'Language';
		languageDescription: 'Select your preferred language';
	};
	device: {
		title: 'Device';
		name: 'Device Name';
		nameDescription: 'User-friendly name for this device';
		slug: 'Device Slug';
		slugDescription: 'Unique identifier for this device (alphanumeric and hyphens only)';
	};
	version: {
		title: 'Version Information';
		version: 'Version';
		built: 'Built';
	};
	dataDirectory: {
		title: 'Data Directory';
		description: 'Where Spacedrive stores its data';
	};
	resetData: {
		title: 'Reset All Data';
		description: 'Permanently delete all libraries and settings';
		confirmTitle: 'Reset All Data';
		confirmMessage: 'This will permanently delete all libraries, settings, and cached data. The app will need to be restarted. Are you sure?';
		successMessage: 'Data has been reset. Please restart the application.';
	};
	sidebar: {
		general: 'General';
		appearance: 'Appearance';
		library: 'Library';
		indexer: 'Indexer';
		services: 'Services';
		privacy: 'Privacy';
		advanced: 'Advanced';
		help: 'Help';
		about: 'About';
		settings: 'Settings';
	};
	help: {
		title: 'Help';
		description: 'Keyboard and mouse controls for the organize preview sidebar.';
		organizeTitle: 'Organize preview shortcuts';
		organizeDescription: 'These shortcuts apply while an image or video preview tab is active in the organize inspector.';
		sections: {
			layout: 'Layout';
			image: 'Image preview';
			video: 'Video preview';
		};
		items: {
			resizeInspector: 'Drag the divider between the browser and the sidebar to resize the preview column.';
			imagePrevious: 'Move to the previous image in the current organize selection.';
			imageNext: 'Move to the next image in the current organize selection.';
			imageZoom: 'Zoom the image preview. Scroll up zooms in, scroll down zooms out.';
			imageOpenWindow: 'Open the selected image in a detached global preview window.';
			videoPrevious: 'Move to the previous or next video in the current organize selection.';
			videoNext: 'Move to the previous or next video in the current organize selection.';
			videoSeek: 'Seek backward or forward by 5 seconds without pausing playback.';
			videoFrameStep: 'Step a single frame and pause playback. Scroll up moves backward, scroll down moves forward.';
			videoToggle: 'Toggle playback by pressing Space or clicking the video surface.';
		};
	};
	fileKinds: {
		title: 'File Kinds';
		subtitle: 'Browse your files by content type';
		totalFiles: 'Total Files';
		file: 'file';
		files: 'files';
		loading: 'Loading file kinds...';
	};
	sources: {
		title: 'Sources';
		searchPlaceholder: 'Search sources...';
		loading: 'Loading...';
		loadError: 'Failed to load sources: {{error}}';
		noSources: 'No sources yet';
		noSourcesDescription: 'Add a data source to get started';
		addSource: 'Add Source';
	};
	redundancy: {
		title: 'Redundancy';
		loading: 'Loading redundancy data...';
		replicationScore: 'Replication Score';
		safelyReplicated: 'safely replicated';
		atRisk: 'at risk (single copy)';
		uniqueContent: 'unique content total';
		filesAtRisk: '{{count}} files at risk';
		oneVolumeData: 'of data exists on only one volume';
		perVolumeBreakdown: 'Per-Volume Breakdown';
		noVolumes: 'No volumes with indexed content found.';
		indexVolumeHint: 'Index a volume to see redundancy data.';
		compareVolumes: 'Compare Volumes';
		viewAtRiskFiles: 'View At-Risk Files';
	};
}

interface SidebarTranslations {
	navigation: {
		overview: 'Overview';
		explorer: 'Explorer';
		favorites: 'Favorites';
		recents: 'Recents';
		fileKinds: 'File Kinds';
		sources: 'Sources';
		adapters: 'Adapters';
		redundancy: 'Redundancy';
		search: 'Search';
		spacebot: 'Spacebot';
		jobs: 'Jobs';
		daemon: 'Daemon';
		settings: 'Settings';
		tags: 'Tags';
	};
	library: {
		switchLibrary: 'Switch Library';
		newLibrary: 'New Library';
		librarySettings: 'Library Settings';
		noLibraries: 'No libraries found';
	};
	sections: {
		devices: 'Devices';
		cloud: 'Cloud';
		locations: 'Locations';
		tags: 'Tags';
	};
	groups: {
		renameGroup: 'Rename Group';
		deleteGroup: 'Delete Group';
		newGroup: 'New Group';
	};
	tags: {
		deleteTag: 'Delete Tag';
		deleteTagConfirm: 'Delete tag "{{name}}"? This will remove it from all files.';
		noTags: 'No tags yet';
		newTag: 'New Tag';
		tagNamePlaceholder: 'Tag name...';
	};
	devices: {
		noDevices: 'No devices';
		unpairDevice: 'Unpair Device';
		removeDevice: 'Remove Device Completely';
	};
	sync: {
		title: 'Sync Monitor';
		peerOnline: '{{count}} peer online';
		peersOnline: '{{count}} peers online';
		openFullMonitor: 'Open full sync monitor';
		showPeers: 'Show peers';
		showActivity: 'Show activity feed';
	};
	jobs: {
		title: 'Job Manager';
		active: '{{count}} active';
		openFull: 'Open full jobs screen';
		showAll: 'Show all jobs';
		showActive: 'Show only active jobs';
	};
	actions: {
		customize: 'Customize';
		settings: 'Settings';
	};
	space: {
		selectSpace: 'Select Space';
		newSpace: 'New Space';
		spaceSettings: 'Space Settings';
		createSpace: 'Create Space';
		spaceName: 'Space Name';
		spaceNamePlaceholder: 'e.g., Work Files, Personal Photos';
		color: 'Color';
		icon: 'Icon';
	};
	customize: {
		title: 'Customize';
		dragToSidebar: 'Drag to sidebar';
		groups: 'Groups';
		addGroup: 'Add Group';
		allDevices: 'All Devices';
		allLocations: 'All Locations';
		cloudStorage: 'Cloud Storage';
		custom: 'Custom';
		customGroup: 'Custom Group';
		groupName: 'Group name';
		groupNamePlaceholder: 'Enter group name';
		groupType: 'Group Type';
		dragItems: 'Drag items to your space';
		device: 'Device';
		group: 'Group';
		add: 'Add';
	};
	volumes: {
		title: 'Volumes';
		noVolumes: 'No volumes';
	};
	sources: {
		title: 'Sources';
	};
	palette: {
		overview: 'Overview';
		recents: 'Recents';
		favorites: 'Favorites';
		fileKinds: 'File Kinds';
		sources: 'Sources';
		redundancy: 'Redundancy';
	};
	fallbacks: {
		unnamedLocation: 'Unnamed Location';
		unnamedVolume: 'Unnamed Volume';
		unnamedTag: 'Unnamed Tag';
		path: 'Path';
		source: 'Source';
		unknown: 'Unknown';
		spacedrive: 'Spacedrive';
		thisDevice: 'This Device';
		tag: 'Tag';
		tagShort: 'Tag: {{id}}...';
		explorer: 'Explorer';
	};
}

export interface Resources {
	common: CommonTranslations;
	dialog: DialogTranslations;
	errors: ErrorsTranslations;
	explorer: ExplorerTranslations;
	overview: OverviewTranslations;
	settings: SettingsTranslations;
	sidebar: SidebarTranslations;
}
