// Auto-generated by scripts/generate-i18n-types.ts — do not edit manually

interface CommonTranslations {
  "actions": {
    "ok": "OK",
    "cancel": "Cancel",
    "save": "Save",
    "delete": "Delete",
    "close": "Close",
    "confirm": "Confirm",
    "back": "Back",
    "next": "Next",
    "reset": "Reset",
    "submit": "Submit",
    "edit": "Edit",
    "copy": "Copy",
    "move": "Move",
    "rename": "Rename",
    "create": "Create",
    "add": "Add",
    "remove": "Remove",
    "search": "Search",
    "filter": "Filter",
    "sort": "Sort",
    "refresh": "Refresh",
    "retry": "Retry",
    "loading": "Loading..."
  },
  "status": {
    "loading": "Loading...",
    "error": "An error occurred",
    "success": "Success",
    "noResults": "No results found",
    "empty": "Nothing here yet",
    "saving": "Saving...",
    "resetting": "Resetting..."
  },
  "units": {
    "bytes": "B",
    "kilobytes": "KB",
    "megabytes": "MB",
    "gigabytes": "GB",
    "terabytes": "TB"
  },
  "time": {
    "justNow": "Just now",
    "minutesAgo": "{{count}} minutes ago",
    "hoursAgo": "{{count}} hours ago",
    "daysAgo": "{{count}} days ago",
    "yesterday": "Yesterday",
    "today": "Today"
  }
}

interface DialogTranslations {
  "confirm": {
    "title": "Confirm",
    "areYouSure": "Are you sure?"
  },
  "delete": {
    "title": "Delete",
    "confirmMessage": "Are you sure you want to delete this item?",
    "confirmMultiple": "Are you sure you want to delete {{count}} items?"
  },
  "rename": {
    "title": "Rename",
    "newName": "New name",
    "placeholder": "Enter new name"
  },
  "create": {
    "library": {
      "title": "Create Library",
      "nameLabel": "Library Name",
      "namePlaceholder": "My Library"
    }
  }
}

interface ErrorsTranslations {
  "LOCATION_NOT_FOUND": "Location not found",
  "LOCATION_ALREADY_EXISTS": "Location already exists",
  "FILE_NOT_FOUND": "File not found",
  "LIBRARY_NOT_FOUND": "Library not found",
  "INSUFFICIENT_PERMISSIONS": "Insufficient permissions",
  "NETWORK_ERROR": "Network connection failed",
  "UNKNOWN": "An unknown error occurred"
}

interface SettingsTranslations {
  "general": {
    "title": "General",
    "description": "Configure general application settings.",
    "language": "Language",
    "languageDescription": "Select your preferred language"
  },
  "device": {
    "title": "Device",
    "name": "Device Name",
    "nameDescription": "User-friendly name for this device",
    "slug": "Device Slug",
    "slugDescription": "Unique identifier for this device (alphanumeric and hyphens only)"
  },
  "version": {
    "title": "Version Information",
    "version": "Version",
    "built": "Built"
  },
  "dataDirectory": {
    "title": "Data Directory",
    "description": "Where Spacedrive stores its data"
  },
  "resetData": {
    "title": "Reset All Data",
    "description": "Permanently delete all libraries and settings",
    "confirmTitle": "Reset All Data",
    "confirmMessage": "This will permanently delete all libraries, settings, and cached data. The app will need to be restarted. Are you sure?",
    "successMessage": "Data has been reset. Please restart the application."
  },
  "sidebar": {
    "general": "General",
    "appearance": "Appearance",
    "library": "Library",
    "indexer": "Indexer",
    "services": "Services",
    "privacy": "Privacy",
    "advanced": "Advanced",
    "about": "About"
  }
}

interface SidebarTranslations {
  "navigation": {
    "overview": "Overview",
    "explorer": "Explorer",
    "favorites": "Favorites",
    "recents": "Recents",
    "fileKinds": "File Kinds",
    "sources": "Sources",
    "adapters": "Adapters",
    "redundancy": "Redundancy",
    "search": "Search",
    "spacebot": "Spacebot",
    "jobs": "Jobs",
    "daemon": "Daemon",
    "settings": "Settings",
    "tags": "Tags"
  },
  "library": {
    "switchLibrary": "Switch Library",
    "newLibrary": "New Library",
    "librarySettings": "Library Settings",
    "noLibraries": "No libraries found"
  },
  "sections": {
    "devices": "Devices",
    "cloud": "Cloud",
    "locations": "Locations",
    "tags": "Tags"
  },
  "groups": {
    "renameGroup": "Rename Group",
    "deleteGroup": "Delete Group",
    "newGroup": "New Group"
  },
  "tags": {
    "deleteTag": "Delete Tag",
    "deleteTagConfirm": "Delete tag \"{{name}}\"? This will remove it from all files.",
    "noTags": "No tags yet",
    "newTag": "New Tag",
    "tagNamePlaceholder": "Tag name..."
  },
  "devices": {
    "noDevices": "No devices",
    "unpairDevice": "Unpair Device",
    "removeDevice": "Remove Device Completely"
  },
  "sync": {
    "title": "Sync Monitor",
    "peerOnline": "{{count}} peer online",
    "peersOnline": "{{count}} peers online",
    "openFullMonitor": "Open full sync monitor",
    "showPeers": "Show peers",
    "showActivity": "Show activity feed"
  },
  "jobs": {
    "title": "Job Manager",
    "active": "{{count}} active",
    "openFull": "Open full jobs screen",
    "showAll": "Show all jobs",
    "showActive": "Show only active jobs"
  },
  "actions": {
    "customize": "Customize",
    "settings": "Settings"
  }
}

export interface Resources {
  'common': CommonTranslations;
  'dialog': DialogTranslations;
  'errors': ErrorsTranslations;
  'settings': SettingsTranslations;
  'sidebar': SidebarTranslations;
}
