import { readFileSync, writeFileSync, readdirSync, mkdirSync } from 'fs';
import { resolve, dirname } from 'path';

const localesDir = resolve(import.meta.dir ?? __dirname, '../src/locales');
const enDir = resolve(localesDir, 'en');
const outDir = resolve(import.meta.dir ?? __dirname, '../src/i18n');
const outFile = resolve(outDir, 'types.d.ts');

function flattenKeys(obj: Record<string, unknown>, prefix = ''): string[] {
  const keys: string[] = [];
  for (const [key, value] of Object.entries(obj)) {
    const fullKey = prefix ? `${prefix}.${key}` : key;
    if (typeof value === 'object' && value !== null && !Array.isArray(value)) {
      keys.push(...flattenKeys(value as Record<string, unknown>, fullKey));
    } else {
      keys.push(fullKey);
    }
  }
  return keys;
}

const namespaces = readdirSync(enDir)
  .filter((f) => f.endsWith('.json'))
  .map((f) => f.replace('.json', ''));

let output = `// Auto-generated by scripts/generate-i18n-types.ts — do not edit manually\n\n`;

for (const ns of namespaces) {
  const content = JSON.parse(readFileSync(resolve(enDir, `${ns}.json`), 'utf-8'));
  const typeName = ns.charAt(0).toUpperCase() + ns.slice(1) + 'Translations';
  output += `interface ${typeName} ${JSON.stringify(content, null, 2)}\n\n`;
}

output += `export interface Resources {\n`;
for (const ns of namespaces) {
  const typeName = ns.charAt(0).toUpperCase() + ns.slice(1) + 'Translations';
  output += `  '${ns}': ${typeName};\n`;
}
output += `}\n`;

mkdirSync(outDir, { recursive: true });
writeFileSync(outFile, output);
console.log(`Generated i18n types: ${outFile}`);
